version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: shopper
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app

  shopper-app:
    build: .
    container_name: shopper-app
    ports:
      - "3000:3000"
    networks:
      - app
    depends_on:
      - postgres
    
networks:
  app:
    driver: bridge

volumes:
  postgres_data: